appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: tI3j/rDZZd3dpYQMGc1o26QkdbfoYPrI3aEjuG1mLVta5UtOfSMQEN9VKrlnOCcjDluUb8yi6SdoGdQpxTy/nR+WxQOKhpLJEiFf4RxOwahnlFS1QcTNpYlcTobzCVerC/MmX/+RuRQt7cz9N2WwrEwQ/VZbx3yN/tORYyeTT4AHf3iQa57nRs6KP/RR6cAytTf4YZsuPsifv7Z1+H/Klm83Aw48NPmdfB2b81zka55fDrZxxfTxY9OzomiCRz07Cth5rz/BlZME8Db8tRVbWazZB0CmcQkvS6SX/ASZlmxUx/S+mq/5Lyvlg+oQj6ufRyLW2wD7mYIaNLfECGNBa4krIuGdGZczXFd8OjiTXEXmC0CUxU0VTsfJejiQgFjQQPMZeZ1tKh7lTXanCKfaGIzm8DRWvXSsY7HGRmUg481MoFUW7t+zA4GjRurMXmxDStKMaI+36zbXuDqLYua2wDDwFFRw9+nr1q75BFKwwk3NQYCS3uJ+9FxUvgBjG4hUINcU9F0f1+eB/LbVYlgvL+KWIyaNmXs1gozvrUUocmM8xXrbaKj0+I7crBvjCoOYxy/KLK0rjGdkYXy/I+fm0jMwdUk7XbT+SixuENcBiJVWImnA8BTYmztxNPWxB2kLl9VBrgfWBZVS4um8kuJUHaPiHpVnS3kiVEdD23heGPQ=
