travis:
  secure:
    BINSTAR_TOKEN: XBluzA8rahMmLfBoVttw9HdgVsBGuzoMZ684SXvFC7CrvTeETP9BEMSc+9/4SPO/m4aO51CH3/HN7Cd4fwuheXJY+cSHZqpd9P/HGljMh4KsXQRY5LpuLa6JzwP3J0QWUk74mk+txhvAi/b1clx3Xhxtza12+LFgXB8qYhmpQMhYJGYC69C5OK3E49kNZuPWWxAuvhISOIJeZCddsC0t+bMqbNbjZ1AY3MZW14VeVzWc+U/1V0y4QLtjhmPQ72VRKZRo69vUWhn0utxfj58VzKZVNLZkvFHNkL/fAJtKh8cYSbFSzcjDUO7+lUSTU1ab1k8jehZ9tjkpdQ3Io3U0WtX03chhNEB1N+y7poXigcmKlElmBppwEZHpI+cj++/ls+P0DL/IB+urMP6ey3jKk13nJhfYUpX60H6dyDnWjCLIwZn8EnjRonwcZ6IJaelNhcJPqxbUFNihxXhnEd4mF6jyogt8EiJPBngB2juatiBdzJdytAAKizih7Fc1OHPxnLczfuF/0B9EjDTWrvUbY01UHPTdj30+0MlGuJ/KMngJmTMBC0TXeVB+TvZn8HR3IElxbicc/Yxr6Btfnemow6EKGJqe1PD0bx2/refUMswhACLsekljW3QzJOLo5wpi0kaC19KfZAOAWkhuDxv2ESfk/KpOM9LvgTXRBsTQZ5E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
